package headers

import (
	"os"
	"reflect"
	"testing"
)

func TestVarHeaders(t *testing.T) {
	t.Run("valid header file", func(t *testing.T) {
		f, err := os.Open("../.testing/valid_test_file.ibt")
		if err != nil {
			t.Errorf("failed to open testing file - %v", err)
			return
		}
		defer f.Close()

		output, err := ReadVarHeader(f, expectedTelemetryHeader.NumVars, expectedTelemetryHeader.VarHeaderOffset)
		if err != nil {
			t.Errorf("failed to parse var header for testing file - %v", err)
			return
		}

		if !reflect.DeepEqual(output, expectedVarHeaders) {
			t.Errorf("expected varHeader does not match actual. \nexpected: %+v\n \nactual: %+v\n", expectedVarHeaders, output)
		}
	})

	t.Run("invalid header file", func(t *testing.T) {
		f, err := os.Open("../.testing/invalid_test_file.ibt")
		if err != nil {
			t.Errorf("failed to open testing file - %v", err)
			return
		}
		defer f.Close()

		_, err = ReadVarHeader(f, expectedTelemetryHeader.NumVars, expectedTelemetryHeader.VarHeaderOffset)
		if err == nil {
			t.Error("expected varHeader parsing of invalid file to return an error")
		}
	})

	t.Run("empty file", func(t *testing.T) {
		f, err := os.Open("../.testing/empty_test_file.ibt")
		if err != nil {
			t.Errorf("failed to open testing file - %v", err)
			return
		}
		defer f.Close()

		_, err = ReadVarHeader(f, expectedTelemetryHeader.NumVars, expectedTelemetryHeader.VarHeaderOffset)
		if err == nil {
			t.Error("expected telemHeader parsing of empty file to return an error")
		}
	})
}

var expectedVarHeaders = map[string]VarHeader{
	"AirDensity": {
		Rtype:       4,
		Offset:      366,
		Count:       1,
		CountAsTime: false,
		Description: "Density of air at start/finish line",
		Name:        "AirDensity",
		Unit:        "kg/m^3",
		Value:       nil,
	},
	"AirPressure": {
		Rtype:       4,
		Offset:      370,
		Count:       1,
		CountAsTime: false,
		Description: "Pressure of air at start/finish line",
		Name:        "AirPressure",
		Unit:        "Pa",
		Value:       nil,
	},
	"AirTemp": {
		Rtype:       4,
		Offset:      354,
		Count:       1,
		CountAsTime: false,
		Description: "Temperature of air at start/finish line",
		Name:        "AirTemp",
		Unit:        "C",
		Value:       nil,
	},
	"Alt": {
		Rtype:       4,
		Offset:      342,
		Count:       1,
		CountAsTime: false,
		Description: "Altitude in meters",
		Name:        "Alt",
		Unit:        "m",
		Value:       nil,
	},
	"Brake": {
		Rtype:       4,
		Offset:      193,
		Count:       1,
		CountAsTime: false,
		Description: "0=brake released to 1=max pedal force",
		Name:        "Brake",
		Unit:        "%",
		Value:       nil,
	},
	"BrakeABSactive": {
		Rtype:       1,
		Offset:      522,
		Count:       1,
		CountAsTime: false,
		Description: "true if abs is currently reducing brake force pressure",
		Name:        "BrakeABSactive",
		Unit:        "",
		Value:       nil,
	},
	"BrakeABScutPct": {
		Rtype:       4,
		Offset:      523,
		Count:       1,
		CountAsTime: false,
		Description: "Percent of brake force reduction caused by ABS system",
		Name:        "BrakeABScutPct",
		Unit:        "%",
		Value:       nil,
	},
	"BrakeRaw": {
		Rtype:       4,
		Offset:      510,
		Count:       1,
		CountAsTime: false,
		Description: "Raw brake input 0=brake released to 1=max pedal force",
		Name:        "BrakeRaw",
		Unit:        "%",
		Value:       nil,
	},
	"CFSRrideHeight": {
		Rtype:       4,
		Offset:      1068,
		Count:       1,
		CountAsTime: false,
		Description: "Center front splitter ride height",
		Name:        "CFSRrideHeight",
		Unit:        "m",
		Value:       nil,
	},
	"CFshockDefl": {
		Rtype:       4,
		Offset:      1020,
		Count:       1,
		CountAsTime: false,
		Description: "CF shock deflection",
		Name:        "CFshockDefl",
		Unit:        "m",
		Value:       nil,
	},
	"CFshockVel": {
		Rtype:       4,
		Offset:      1024,
		Count:       1,
		CountAsTime: false,
		Description: "CF shock velocity",
		Name:        "CFshockVel",
		Unit:        "m/s",
		Value:       nil,
	},
	"CRshockDefl": {
		Rtype:       4,
		Offset:      1036,
		Count:       1,
		CountAsTime: false,
		Description: "CR shock deflection",
		Name:        "CRshockDefl",
		Unit:        "m",
		Value:       nil,
	},
	"CRshockVel": {
		Rtype:       4,
		Offset:      1040,
		Count:       1,
		CountAsTime: false,
		Description: "CR shock velocity",
		Name:        "CRshockVel",
		Unit:        "m/s",
		Value:       nil,
	},
	"ChanAvgLatency": {
		Rtype:       4,
		Offset:      83,
		Count:       1,
		CountAsTime: false,
		Description: "Communications average latency",
		Name:        "ChanAvgLatency",
		Unit:        "s",
		Value:       nil,
	},
	"ChanClockSkew": {
		Rtype:       4,
		Offset:      103,
		Count:       1,
		CountAsTime: false,
		Description: "Communications server clock skew",
		Name:        "ChanClockSkew",
		Unit:        "s",
		Value:       nil,
	},
	"ChanLatency": {
		Rtype:       4,
		Offset:      87,
		Count:       1,
		CountAsTime: false,
		Description: "Communications latency",
		Name:        "ChanLatency",
		Unit:        "s",
		Value:       nil,
	},
	"ChanPartnerQuality": {
		Rtype:       4,
		Offset:      95,
		Count:       1,
		CountAsTime: false,
		Description: "Partner communications quality",
		Name:        "ChanPartnerQuality",
		Unit:        "%",
		Value:       nil,
	},
	"ChanQuality": {
		Rtype:       4,
		Offset:      91,
		Count:       1,
		CountAsTime: false,
		Description: "Communications quality",
		Name:        "ChanQuality",
		Unit:        "%",
		Value:       nil,
	},
	"Clutch": {
		Rtype:       4,
		Offset:      197,
		Count:       1,
		CountAsTime: false,
		Description: "0=disengaged to 1=fully engaged",
		Name:        "Clutch",
		Unit:        "%",
		Value:       nil,
	},
	"ClutchRaw": {
		Rtype:       4,
		Offset:      514,
		Count:       1,
		CountAsTime: false,
		Description: "Raw clutch input 0=disengaged to 1=fully engaged",
		Name:        "ClutchRaw",
		Unit:        "%",
		Value:       nil,
	},
	"CpuUsageBG": {
		Rtype:       4,
		Offset:      99,
		Count:       1,
		CountAsTime: false,
		Description: "Percent of available tim bg thread took with a 1 sec avg",
		Name:        "CpuUsageBG",
		Unit:        "%",
		Value:       nil,
	},
	"CpuUsageFG": {
		Rtype:       4,
		Offset:      75,
		Count:       1,
		CountAsTime: false,
		Description: "Percent of available tim fg thread took with a 1 sec avg",
		Name:        "CpuUsageFG",
		Unit:        "%",
		Value:       nil,
	},
	"DRS_Status": {
		Rtype:       2,
		Offset:      752,
		Count:       1,
		CountAsTime: false,
		Description: "Drag Reduction System Status",
		Name:        "DRS_Status",
		Unit:        " ",
		Value:       nil,
	},
	"DriverMarker": {
		Rtype:       1,
		Offset:      65,
		Count:       1,
		CountAsTime: false,
		Description: "Driver activated flag",
		Name:        "DriverMarker",
		Unit:        "",
		Value:       nil,
	},
	"EnergyBatteryToMGU_KLap": {
		Rtype:       4,
		Offset:      908,
		Count:       1,
		CountAsTime: false,
		Description: "Electrical energy from battery to MGU-K per lap",
		Name:        "EnergyBatteryToMGU_KLap",
		Unit:        "J",
		Value:       nil,
	},
	"EnergyERSBattery": {
		Rtype:       4,
		Offset:      900,
		Count:       1,
		CountAsTime: false,
		Description: "Engine ERS battery charge",
		Name:        "EnergyERSBattery",
		Unit:        "J",
		Value:       nil,
	},
	"EnergyERSBatteryPct": {
		Rtype:       4,
		Offset:      904,
		Count:       1,
		CountAsTime: false,
		Description: "Engine ERS battery charge as a percent",
		Name:        "EnergyERSBatteryPct",
		Unit:        "%",
		Value:       nil,
	},
	"EnergyMGU_KLapDeployPct": {
		Rtype:       4,
		Offset:      912,
		Count:       1,
		CountAsTime: false,
		Description: "Electrical energy available to MGU-K per lap as a percent",
		Name:        "EnergyMGU_KLapDeployPct",
		Unit:        "%",
		Value:       nil,
	},
	"Engine0_RPM": {
		Rtype:       4,
		Offset:      920,
		Count:       1,
		CountAsTime: false,
		Description: "Engine0Engine rpm",
		Name:        "Engine0_RPM",
		Unit:        "revs/min",
		Value:       nil,
	},
	"EngineWarnings": {
		Rtype:       3,
		Offset:      527,
		Count:       1,
		CountAsTime: false,
		Description: "Bitfield for warning lights",
		Name:        "EngineWarnings",
		Unit:        "irsdk_EngineWarnings",
		Value:       nil,
	},
	"EnterExitReset": {
		Rtype:       2,
		Offset:      322,
		Count:       1,
		CountAsTime: false,
		Description: "Indicate action the reset key will take 0 enter 1 exit 2 reset",
		Name:        "EnterExitReset",
		Unit:        "",
		Value:       nil,
	},
	"FastRepairAvailable": {
		Rtype:       2,
		Offset:      417,
		Count:       1,
		CountAsTime: false,
		Description: "How many fast repairs left  255 is unlimited",
		Name:        "FastRepairAvailable",
		Unit:        "",
		Value:       nil,
	},
	"FastRepairUsed": {
		Rtype:       2,
		Offset:      413,
		Count:       1,
		CountAsTime: false,
		Description: "How many fast repairs used so far",
		Name:        "FastRepairUsed",
		Unit:        "",
		Value:       nil,
	},
	"FogLevel": {
		Rtype:       4,
		Offset:      386,
		Count:       1,
		CountAsTime: false,
		Description: "Fog level at start/finish line",
		Name:        "FogLevel",
		Unit:        "%",
		Value:       nil,
	},
	"FrameRate": {
		Rtype:       4,
		Offset:      71,
		Count:       1,
		CountAsTime: false,
		Description: "Average frames per second",
		Name:        "FrameRate",
		Unit:        "fps",
		Value:       nil,
	},
	"FrontTireSetsAvailable": {
		Rtype:       2,
		Offset:      481,
		Count:       1,
		CountAsTime: false,
		Description: "How many front tire sets are remaining  255 is unlimited",
		Name:        "FrontTireSetsAvailable",
		Unit:        "",
		Value:       nil,
	},
	"FrontTireSetsUsed": {
		Rtype:       2,
		Offset:      445,
		Count:       1,
		CountAsTime: false,
		Description: "How many front tire sets used so far",
		Name:        "FrontTireSetsUsed",
		Unit:        "",
		Value:       nil,
	},
	"FuelLevel": {
		Rtype:       4,
		Offset:      916,
		Count:       1,
		CountAsTime: false,
		Description: "Liters of fuel remaining",
		Name:        "FuelLevel",
		Unit:        "l",
		Value:       nil,
	},
	"FuelLevelPct": {
		Rtype:       4,
		Offset:      531,
		Count:       1,
		CountAsTime: false,
		Description: "Percent fuel remaining",
		Name:        "FuelLevelPct",
		Unit:        "%",
		Value:       nil,
	},
	"FuelPress": {
		Rtype:       4,
		Offset:      868,
		Count:       1,
		CountAsTime: false,
		Description: "Engine fuel pressure",
		Name:        "FuelPress",
		Unit:        "bar",
		Value:       nil,
	},
	"FuelUsePerHour": {
		Rtype:       4,
		Offset:      852,
		Count:       1,
		CountAsTime: false,
		Description: "Engine fuel used instantaneous",
		Name:        "FuelUsePerHour",
		Unit:        "kg/h",
		Value:       nil,
	},
	"Gear": {
		Rtype:       2,
		Offset:      201,
		Count:       1,
		CountAsTime: false,
		Description: "-1=reverse  0=neutral  1..n=current gear",
		Name:        "Gear",
		Unit:        "",
		Value:       nil,
	},
	"GpuUsage": {
		Rtype:       4,
		Offset:      79,
		Count:       1,
		CountAsTime: false,
		Description: "Percent of available tim gpu took with a 1 sec avg",
		Name:        "GpuUsage",
		Unit:        "%",
		Value:       nil,
	},
	"HandbrakeRaw": {
		Rtype:       4,
		Offset:      518,
		Count:       1,
		CountAsTime: false,
		Description: "Raw handbrake input 0=handbrake released to 1=max force",
		Name:        "HandbrakeRaw",
		Unit:        "%",
		Value:       nil,
	},
	"IsOnTrack": {
		Rtype:       1,
		Offset:      70,
		Count:       1,
		CountAsTime: false,
		Description: "1=Car on track physics running with player in car",
		Name:        "IsOnTrack",
		Unit:        "",
		Value:       nil,
	},
	"IsOnTrackCar": {
		Rtype:       1,
		Offset:      493,
		Count:       1,
		CountAsTime: false,
		Description: "1=Car on track physics running",
		Name:        "IsOnTrackCar",
		Unit:        "",
		Value:       nil,
	},
	"LFTiresAvailable": {
		Rtype:       2,
		Offset:      457,
		Count:       1,
		CountAsTime: false,
		Description: "How many left front tires are remaining  255 is unlimited",
		Name:        "LFTiresAvailable",
		Unit:        "",
		Value:       nil,
	},
	"LFTiresUsed": {
		Rtype:       2,
		Offset:      421,
		Count:       1,
		CountAsTime: false,
		Description: "How many left front tires used so far",
		Name:        "LFTiresUsed",
		Unit:        "",
		Value:       nil,
	},
	"LFcoldPressure": {
		Rtype:       4,
		Offset:      812,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire cold pressure  as set in the garage",
		Name:        "LFcoldPressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"LFpressure": {
		Rtype:       4,
		Offset:      808,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire pressure",
		Name:        "LFpressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"LFrideHeight": {
		Rtype:       4,
		Offset:      1052,
		Count:       1,
		CountAsTime: false,
		Description: "LF ride height",
		Name:        "LFrideHeight",
		Unit:        "m",
		Value:       nil,
	},
	"LFspeed": {
		Rtype:       4,
		Offset:      804,
		Count:       1,
		CountAsTime: false,
		Description: "LF wheel speed",
		Name:        "LFspeed",
		Unit:        "m/s",
		Value:       nil,
	},
	"LFtempCL": {
		Rtype:       4,
		Offset:      828,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire left carcass temperature",
		Name:        "LFtempCL",
		Unit:        "C",
		Value:       nil,
	},
	"LFtempCM": {
		Rtype:       4,
		Offset:      832,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire middle carcass temperature",
		Name:        "LFtempCM",
		Unit:        "C",
		Value:       nil,
	},
	"LFtempCR": {
		Rtype:       4,
		Offset:      836,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire right carcass temperature",
		Name:        "LFtempCR",
		Unit:        "C",
		Value:       nil,
	},
	"LFtempL": {
		Rtype:       4,
		Offset:      816,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire left surface temperature",
		Name:        "LFtempL",
		Unit:        "C",
		Value:       nil,
	},
	"LFtempM": {
		Rtype:       4,
		Offset:      820,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire middle surface temperature",
		Name:        "LFtempM",
		Unit:        "C",
		Value:       nil,
	},
	"LFtempR": {
		Rtype:       4,
		Offset:      824,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire right surface temperature",
		Name:        "LFtempR",
		Unit:        "C",
		Value:       nil,
	},
	"LFwearL": {
		Rtype:       4,
		Offset:      840,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire left percent tread remaining",
		Name:        "LFwearL",
		Unit:        "%",
		Value:       nil,
	},
	"LFwearM": {
		Rtype:       4,
		Offset:      844,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire middle percent tread remaining",
		Name:        "LFwearM",
		Unit:        "%",
		Value:       nil,
	},
	"LFwearR": {
		Rtype:       4,
		Offset:      848,
		Count:       1,
		CountAsTime: false,
		Description: "LF tire right percent tread remaining",
		Name:        "LFwearR",
		Unit:        "%",
		Value:       nil,
	},
	"LRTiresAvailable": {
		Rtype:       2,
		Offset:      465,
		Count:       1,
		CountAsTime: false,
		Description: "How many left rear tires are remaining  255 is unlimited",
		Name:        "LRTiresAvailable",
		Unit:        "",
		Value:       nil,
	},
	"LRTiresUsed": {
		Rtype:       2,
		Offset:      429,
		Count:       1,
		CountAsTime: false,
		Description: "How many left rear tires used so far",
		Name:        "LRTiresUsed",
		Unit:        "",
		Value:       nil,
	},
	"LRcoldPressure": {
		Rtype:       4,
		Offset:      980,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire cold pressure  as set in the garage",
		Name:        "LRcoldPressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"LRpressure": {
		Rtype:       4,
		Offset:      976,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire pressure",
		Name:        "LRpressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"LRrideHeight": {
		Rtype:       4,
		Offset:      1060,
		Count:       1,
		CountAsTime: false,
		Description: "LR ride height",
		Name:        "LRrideHeight",
		Unit:        "m",
		Value:       nil,
	},
	"LRspeed": {
		Rtype:       4,
		Offset:      972,
		Count:       1,
		CountAsTime: false,
		Description: "LR wheel speed",
		Name:        "LRspeed",
		Unit:        "m/s",
		Value:       nil,
	},
	"LRtempCL": {
		Rtype:       4,
		Offset:      996,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire left carcass temperature",
		Name:        "LRtempCL",
		Unit:        "C",
		Value:       nil,
	},
	"LRtempCM": {
		Rtype:       4,
		Offset:      1000,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire middle carcass temperature",
		Name:        "LRtempCM",
		Unit:        "C",
		Value:       nil,
	},
	"LRtempCR": {
		Rtype:       4,
		Offset:      1004,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire right carcass temperature",
		Name:        "LRtempCR",
		Unit:        "C",
		Value:       nil,
	},
	"LRtempL": {
		Rtype:       4,
		Offset:      984,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire left surface temperature",
		Name:        "LRtempL",
		Unit:        "C",
		Value:       nil,
	},
	"LRtempM": {
		Rtype:       4,
		Offset:      988,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire middle surface temperature",
		Name:        "LRtempM",
		Unit:        "C",
		Value:       nil,
	},
	"LRtempR": {
		Rtype:       4,
		Offset:      992,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire right surface temperature",
		Name:        "LRtempR",
		Unit:        "C",
		Value:       nil,
	},
	"LRwearL": {
		Rtype:       4,
		Offset:      1008,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire left percent tread remaining",
		Name:        "LRwearL",
		Unit:        "%",
		Value:       nil,
	},
	"LRwearM": {
		Rtype:       4,
		Offset:      1012,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire middle percent tread remaining",
		Name:        "LRwearM",
		Unit:        "%",
		Value:       nil,
	},
	"LRwearR": {
		Rtype:       4,
		Offset:      1016,
		Count:       1,
		CountAsTime: false,
		Description: "LR tire right percent tread remaining",
		Name:        "LRwearR",
		Unit:        "%",
		Value:       nil,
	},
	"Lap": {
		Rtype:       2,
		Offset:      209,
		Count:       1,
		CountAsTime: false,
		Description: "Laps started count",
		Name:        "Lap",
		Unit:        "",
		Value:       nil,
	},
	"LapBestLap": {
		Rtype:       2,
		Offset:      225,
		Count:       1,
		CountAsTime: false,
		Description: "Players best lap number",
		Name:        "LapBestLap",
		Unit:        "",
		Value:       nil,
	},
	"LapBestLapTime": {
		Rtype:       4,
		Offset:      229,
		Count:       1,
		CountAsTime: false,
		Description: "Players best lap time",
		Name:        "LapBestLapTime",
		Unit:        "s",
		Value:       nil,
	},
	"LapBestNLapLap": {
		Rtype:       2,
		Offset:      249,
		Count:       1,
		CountAsTime: false,
		Description: "Player last lap in best N average lap time",
		Name:        "LapBestNLapLap",
		Unit:        "",
		Value:       nil,
	},
	"LapBestNLapTime": {
		Rtype:       4,
		Offset:      253,
		Count:       1,
		CountAsTime: false,
		Description: "Player best N average lap time",
		Name:        "LapBestNLapTime",
		Unit:        "s",
		Value:       nil,
	},
	"LapCompleted": {
		Rtype:       2,
		Offset:      213,
		Count:       1,
		CountAsTime: false,
		Description: "Laps completed count",
		Name:        "LapCompleted",
		Unit:        "",
		Value:       nil,
	},
	"LapCurrentLapTime": {
		Rtype:       4,
		Offset:      237,
		Count:       1,
		CountAsTime: false,
		Description: "Estimate of players current lap time as shown in F3 box",
		Name:        "LapCurrentLapTime",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToBestLap": {
		Rtype:       4,
		Offset:      257,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for best lap",
		Name:        "LapDeltaToBestLap",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToBestLap_DD": {
		Rtype:       4,
		Offset:      261,
		Count:       1,
		CountAsTime: false,
		Description: "Rate of change of delta time for best lap",
		Name:        "LapDeltaToBestLap_DD",
		Unit:        "s/s",
		Value:       nil,
	},
	"LapDeltaToBestLap_OK": {
		Rtype:       1,
		Offset:      265,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for best lap is valid",
		Name:        "LapDeltaToBestLap_OK",
		Unit:        "",
		Value:       nil,
	},
	"LapDeltaToOptimalLap": {
		Rtype:       4,
		Offset:      266,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for optimal lap",
		Name:        "LapDeltaToOptimalLap",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToOptimalLap_DD": {
		Rtype:       4,
		Offset:      270,
		Count:       1,
		CountAsTime: false,
		Description: "Rate of change of delta time for optimal lap",
		Name:        "LapDeltaToOptimalLap_DD",
		Unit:        "s/s",
		Value:       nil,
	},
	"LapDeltaToOptimalLap_OK": {
		Rtype:       1,
		Offset:      274,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for optimal lap is valid",
		Name:        "LapDeltaToOptimalLap_OK",
		Unit:        "",
		Value:       nil,
	},
	"LapDeltaToSessionBestLap": {
		Rtype:       4,
		Offset:      275,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session best lap",
		Name:        "LapDeltaToSessionBestLap",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToSessionBestLap_DD": {
		Rtype:       4,
		Offset:      279,
		Count:       1,
		CountAsTime: false,
		Description: "Rate of change of delta time for session best lap",
		Name:        "LapDeltaToSessionBestLap_DD",
		Unit:        "s/s",
		Value:       nil,
	},
	"LapDeltaToSessionBestLap_OK": {
		Rtype:       1,
		Offset:      283,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session best lap is valid",
		Name:        "LapDeltaToSessionBestLap_OK",
		Unit:        "",
		Value:       nil,
	},
	"LapDeltaToSessionLastlLap": {
		Rtype:       4,
		Offset:      293,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session last lap",
		Name:        "LapDeltaToSessionLastlLap",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToSessionLastlLap_DD": {
		Rtype:       4,
		Offset:      297,
		Count:       1,
		CountAsTime: false,
		Description: "Rate of change of delta time for session last lap",
		Name:        "LapDeltaToSessionLastlLap_DD",
		Unit:        "s/s",
		Value:       nil,
	},
	"LapDeltaToSessionLastlLap_OK": {
		Rtype:       1,
		Offset:      301,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session last lap is valid",
		Name:        "LapDeltaToSessionLastlLap_OK",
		Unit:        "",
		Value:       nil,
	},
	"LapDeltaToSessionOptimalLap": {
		Rtype:       4,
		Offset:      284,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session optimal lap",
		Name:        "LapDeltaToSessionOptimalLap",
		Unit:        "s",
		Value:       nil,
	},
	"LapDeltaToSessionOptimalLap_DD": {
		Rtype:       4,
		Offset:      288,
		Count:       1,
		CountAsTime: false,
		Description: "Rate of change of delta time for session optimal lap",
		Name:        "LapDeltaToSessionOptimalLap_DD",
		Unit:        "s/s",
		Value:       nil,
	},
	"LapDeltaToSessionOptimalLap_OK": {
		Rtype:       1,
		Offset:      292,
		Count:       1,
		CountAsTime: false,
		Description: "Delta time for session optimal lap is valid",
		Name:        "LapDeltaToSessionOptimalLap_OK",
		Unit:        "",
		Value:       nil,
	},
	"LapDist": {
		Rtype:       4,
		Offset:      217,
		Count:       1,
		CountAsTime: false,
		Description: "Meters traveled from S/F this lap",
		Name:        "LapDist",
		Unit:        "m",
		Value:       nil,
	},
	"LapDistPct": {
		Rtype:       4,
		Offset:      221,
		Count:       1,
		CountAsTime: false,
		Description: "Percentage distance around lap",
		Name:        "LapDistPct",
		Unit:        "%",
		Value:       nil,
	},
	"LapLasNLapSeq": {
		Rtype:       2,
		Offset:      241,
		Count:       1,
		CountAsTime: false,
		Description: "Player num consecutive clean laps completed for N average",
		Name:        "LapLasNLapSeq",
		Unit:        "",
		Value:       nil,
	},
	"LapLastLapTime": {
		Rtype:       4,
		Offset:      233,
		Count:       1,
		CountAsTime: false,
		Description: "Players last lap time",
		Name:        "LapLastLapTime",
		Unit:        "s",
		Value:       nil,
	},
	"LapLastNLapTime": {
		Rtype:       4,
		Offset:      245,
		Count:       1,
		CountAsTime: false,
		Description: "Player last N average lap time",
		Name:        "LapLastNLapTime",
		Unit:        "s",
		Value:       nil,
	},
	"Lat": {
		Rtype:       5,
		Offset:      326,
		Count:       1,
		CountAsTime: false,
		Description: "Latitude in decimal degrees",
		Name:        "Lat",
		Unit:        "deg",
		Value:       nil,
	},
	"LatAccel": {
		Rtype:       4,
		Offset:      672,
		Count:       1,
		CountAsTime: false,
		Description: "Lateral acceleration (including gravity)",
		Name:        "LatAccel",
		Unit:        "m/s^2",
		Value:       nil,
	},
	"LeftTireSetsAvailable": {
		Rtype:       2,
		Offset:      473,
		Count:       1,
		CountAsTime: false,
		Description: "How many left tire sets are remaining  255 is unlimited",
		Name:        "LeftTireSetsAvailable",
		Unit:        "",
		Value:       nil,
	},
	"LeftTireSetsUsed": {
		Rtype:       2,
		Offset:      437,
		Count:       1,
		CountAsTime: false,
		Description: "How many left tire sets used so far",
		Name:        "LeftTireSetsUsed",
		Unit:        "",
		Value:       nil,
	},
	"Lon": {
		Rtype:       5,
		Offset:      334,
		Count:       1,
		CountAsTime: false,
		Description: "Longitude in decimal degrees",
		Name:        "Lon",
		Unit:        "deg",
		Value:       nil,
	},
	"LongAccel": {
		Rtype:       4,
		Offset:      676,
		Count:       1,
		CountAsTime: false,
		Description: "Longitudinal acceleration (including gravity)",
		Name:        "LongAccel",
		Unit:        "m/s^2",
		Value:       nil,
	},
	"ManifoldPress": {
		Rtype:       4,
		Offset:      884,
		Count:       1,
		CountAsTime: false,
		Description: "Engine manifold pressure",
		Name:        "ManifoldPress",
		Unit:        "bar",
		Value:       nil,
	},
	"ManualBoost": {
		Rtype:       1,
		Offset:      68,
		Count:       1,
		CountAsTime: false,
		Description: "Hybrid manual boost state",
		Name:        "ManualBoost",
		Unit:        "",
		Value:       nil,
	},
	"ManualNoBoost": {
		Rtype:       1,
		Offset:      69,
		Count:       1,
		CountAsTime: false,
		Description: "Hybrid manual no boost state",
		Name:        "ManualNoBoost",
		Unit:        "",
		Value:       nil,
	},
	"MemPageFaultSec": {
		Rtype:       4,
		Offset:      107,
		Count:       1,
		CountAsTime: false,
		Description: "Memory page faults per second",
		Name:        "MemPageFaultSec",
		Unit:        "",
		Value:       nil,
	},
	"MemSoftPageFaultSec": {
		Rtype:       4,
		Offset:      111,
		Count:       1,
		CountAsTime: false,
		Description: "Memory soft page faults per second",
		Name:        "MemSoftPageFaultSec",
		Unit:        "",
		Value:       nil,
	},
	"OilLevel": {
		Rtype:       4,
		Offset:      880,
		Count:       1,
		CountAsTime: false,
		Description: "Engine oil level",
		Name:        "OilLevel",
		Unit:        "l",
		Value:       nil,
	},
	"OilPress": {
		Rtype:       4,
		Offset:      876,
		Count:       1,
		CountAsTime: false,
		Description: "Engine oil pressure",
		Name:        "OilPress",
		Unit:        "bar",
		Value:       nil,
	},
	"OilTemp": {
		Rtype:       4,
		Offset:      872,
		Count:       1,
		CountAsTime: false,
		Description: "Engine oil temperature",
		Name:        "OilTemp",
		Unit:        "C",
		Value:       nil,
	},
	"OnPitRoad": {
		Rtype:       1,
		Offset:      184,
		Count:       1,
		CountAsTime: false,
		Description: "Is the player car on pit road between the cones",
		Name:        "OnPitRoad",
		Unit:        "",
		Value:       nil,
	},
	"PaceMode": {
		Rtype:       2,
		Offset:      180,
		Count:       1,
		CountAsTime: false,
		Description: "Are we pacing or not",
		Name:        "PaceMode",
		Unit:        "irsdk_PaceMode",
		Value:       nil,
	},
	"PitOptRepairLeft": {
		Rtype:       4,
		Offset:      408,
		Count:       1,
		CountAsTime: false,
		Description: "Time left for optional repairs if repairs are active",
		Name:        "PitOptRepairLeft",
		Unit:        "s",
		Value:       nil,
	},
	"PitRepairLeft": {
		Rtype:       4,
		Offset:      404,
		Count:       1,
		CountAsTime: false,
		Description: "Time left for mandatory pit repairs if repairs are active",
		Name:        "PitRepairLeft",
		Unit:        "s",
		Value:       nil,
	},
	"PitSvFlags": {
		Rtype:       3,
		Offset:      535,
		Count:       1,
		CountAsTime: false,
		Description: "Bitfield of pit service checkboxes",
		Name:        "PitSvFlags",
		Unit:        "irsdk_PitSvFlags",
		Value:       nil,
	},
	"PitSvFuel": {
		Rtype:       4,
		Offset:      555,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service fuel add amount",
		Name:        "PitSvFuel",
		Unit:        "l or kWh",
		Value:       nil,
	},
	"PitSvLFP": {
		Rtype:       4,
		Offset:      539,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service left front tire pressure",
		Name:        "PitSvLFP",
		Unit:        "kPa",
		Value:       nil,
	},
	"PitSvLRP": {
		Rtype:       4,
		Offset:      547,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service left rear tire pressure",
		Name:        "PitSvLRP",
		Unit:        "kPa",
		Value:       nil,
	},
	"PitSvRFP": {
		Rtype:       4,
		Offset:      543,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service right front tire pressure",
		Name:        "PitSvRFP",
		Unit:        "kPa",
		Value:       nil,
	},
	"PitSvRRP": {
		Rtype:       4,
		Offset:      551,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service right rear tire pressure",
		Name:        "PitSvRRP",
		Unit:        "kPa",
		Value:       nil,
	},
	"PitSvTireCompound": {
		Rtype:       2,
		Offset:      559,
		Count:       1,
		CountAsTime: false,
		Description: "Pit service pending tire compound",
		Name:        "PitSvTireCompound",
		Unit:        "",
		Value:       nil,
	},
	"Pitch": {
		Rtype:       4,
		Offset:      314,
		Count:       1,
		CountAsTime: false,
		Description: "Pitch orientation",
		Name:        "Pitch",
		Unit:        "rad",
		Value:       nil,
	},
	"PitchRate": {
		Rtype:       4,
		Offset:      660,
		Count:       1,
		CountAsTime: false,
		Description: "Pitch rate",
		Name:        "PitchRate",
		Unit:        "rad/s",
		Value:       nil,
	},
	"PitsOpen": {
		Rtype:       1,
		Offset:      403,
		Count:       1,
		CountAsTime: false,
		Description: "True if pit stop is allowed for the current player",
		Name:        "PitsOpen",
		Unit:        "",
		Value:       nil,
	},
	"PitstopActive": {
		Rtype:       1,
		Offset:      412,
		Count:       1,
		CountAsTime: false,
		Description: "Is the player getting pit stop service",
		Name:        "PitstopActive",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarClass": {
		Rtype:       2,
		Offset:      123,
		Count:       1,
		CountAsTime: false,
		Description: "Player car class id",
		Name:        "PlayerCarClass",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarClassPosition": {
		Rtype:       2,
		Offset:      119,
		Count:       1,
		CountAsTime: false,
		Description: "Players class position in race",
		Name:        "PlayerCarClassPosition",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarDriverIncidentCount": {
		Rtype:       2,
		Offset:      147,
		Count:       1,
		CountAsTime: false,
		Description: "Teams current drivers incident count for this session",
		Name:        "PlayerCarDriverIncidentCount",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarDryTireSetLimit": {
		Rtype:       2,
		Offset:      159,
		Count:       1,
		CountAsTime: false,
		Description: "Players dry tire set limit",
		Name:        "PlayerCarDryTireSetLimit",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarIdx": {
		Rtype:       2,
		Offset:      135,
		Count:       1,
		CountAsTime: false,
		Description: "Players carIdx",
		Name:        "PlayerCarIdx",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarInPitStall": {
		Rtype:       1,
		Offset:      167,
		Count:       1,
		CountAsTime: false,
		Description: "Players car is properly in their pitstall",
		Name:        "PlayerCarInPitStall",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarMyIncidentCount": {
		Rtype:       2,
		Offset:      143,
		Count:       1,
		CountAsTime: false,
		Description: "Players own incident count for this session",
		Name:        "PlayerCarMyIncidentCount",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarPitSvStatus": {
		Rtype:       2,
		Offset:      168,
		Count:       1,
		CountAsTime: false,
		Description: "Players car pit service status bits",
		Name:        "PlayerCarPitSvStatus",
		Unit:        "irsdk_PitSvStatus",
		Value:       nil,
	},
	"PlayerCarPosition": {
		Rtype:       2,
		Offset:      115,
		Count:       1,
		CountAsTime: false,
		Description: "Players position in race",
		Name:        "PlayerCarPosition",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarPowerAdjust": {
		Rtype:       4,
		Offset:      155,
		Count:       1,
		CountAsTime: false,
		Description: "Players power adjust",
		Name:        "PlayerCarPowerAdjust",
		Unit:        "%",
		Value:       nil,
	},
	"PlayerCarTeamIncidentCount": {
		Rtype:       2,
		Offset:      139,
		Count:       1,
		CountAsTime: false,
		Description: "Players team incident count for this session",
		Name:        "PlayerCarTeamIncidentCount",
		Unit:        "",
		Value:       nil,
	},
	"PlayerCarTowTime": {
		Rtype:       4,
		Offset:      163,
		Count:       1,
		CountAsTime: false,
		Description: "Players car is being towed if time is greater than zero",
		Name:        "PlayerCarTowTime",
		Unit:        "s",
		Value:       nil,
	},
	"PlayerCarWeightPenalty": {
		Rtype:       4,
		Offset:      151,
		Count:       1,
		CountAsTime: false,
		Description: "Players weight penalty",
		Name:        "PlayerCarWeightPenalty",
		Unit:        "kg",
		Value:       nil,
	},
	"PlayerFastRepairsUsed": {
		Rtype:       2,
		Offset:      176,
		Count:       1,
		CountAsTime: false,
		Description: "Players car number of fast repairs used",
		Name:        "PlayerFastRepairsUsed",
		Unit:        "",
		Value:       nil,
	},
	"PlayerTireCompound": {
		Rtype:       2,
		Offset:      172,
		Count:       1,
		CountAsTime: false,
		Description: "Players car current tire compound",
		Name:        "PlayerTireCompound",
		Unit:        "",
		Value:       nil,
	},
	"PlayerTrackSurface": {
		Rtype:       2,
		Offset:      127,
		Count:       1,
		CountAsTime: false,
		Description: "Players car track surface type",
		Name:        "PlayerTrackSurface",
		Unit:        "irsdk_TrkLoc",
		Value:       nil,
	},
	"PlayerTrackSurfaceMaterial": {
		Rtype:       2,
		Offset:      131,
		Count:       1,
		CountAsTime: false,
		Description: "Players car track surface material type",
		Name:        "PlayerTrackSurfaceMaterial",
		Unit:        "irsdk_TrkSurf",
		Value:       nil,
	},
	"PowerMGU_H": {
		Rtype:       4,
		Offset:      896,
		Count:       1,
		CountAsTime: false,
		Description: "Engine MGU-H mechanical power",
		Name:        "PowerMGU_H",
		Unit:        "W",
		Value:       nil,
	},
	"PowerMGU_K": {
		Rtype:       4,
		Offset:      888,
		Count:       1,
		CountAsTime: false,
		Description: "Engine MGU-K mechanical power",
		Name:        "PowerMGU_K",
		Unit:        "W",
		Value:       nil,
	},
	"Precipitation": {
		Rtype:       4,
		Offset:      390,
		Count:       1,
		CountAsTime: false,
		Description: "Precipitation at start/finish line",
		Name:        "Precipitation",
		Unit:        "%",
		Value:       nil,
	},
	"PushToPass": {
		Rtype:       1,
		Offset:      67,
		Count:       1,
		CountAsTime: false,
		Description: "Push to pass button state",
		Name:        "PushToPass",
		Unit:        "",
		Value:       nil,
	},
	"PushToTalk": {
		Rtype:       1,
		Offset:      66,
		Count:       1,
		CountAsTime: false,
		Description: "Push to talk button state",
		Name:        "PushToTalk",
		Unit:        "",
		Value:       nil,
	},
	"RFTiresAvailable": {
		Rtype:       2,
		Offset:      461,
		Count:       1,
		CountAsTime: false,
		Description: "How many right front tires are remaining  255 is unlimited",
		Name:        "RFTiresAvailable",
		Unit:        "",
		Value:       nil,
	},
	"RFTiresUsed": {
		Rtype:       2,
		Offset:      425,
		Count:       1,
		CountAsTime: false,
		Description: "How many right front tires used so far",
		Name:        "RFTiresUsed",
		Unit:        "",
		Value:       nil,
	},
	"RFcoldPressure": {
		Rtype:       4,
		Offset:      764,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire cold pressure  as set in the garage",
		Name:        "RFcoldPressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"RFpressure": {
		Rtype:       4,
		Offset:      760,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire pressure",
		Name:        "RFpressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"RFrideHeight": {
		Rtype:       4,
		Offset:      1056,
		Count:       1,
		CountAsTime: false,
		Description: "RF ride height",
		Name:        "RFrideHeight",
		Unit:        "m",
		Value:       nil,
	},
	"RFspeed": {
		Rtype:       4,
		Offset:      756,
		Count:       1,
		CountAsTime: false,
		Description: "RF wheel speed",
		Name:        "RFspeed",
		Unit:        "m/s",
		Value:       nil,
	},
	"RFtempCL": {
		Rtype:       4,
		Offset:      780,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire left carcass temperature",
		Name:        "RFtempCL",
		Unit:        "C",
		Value:       nil,
	},
	"RFtempCM": {
		Rtype:       4,
		Offset:      784,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire middle carcass temperature",
		Name:        "RFtempCM",
		Unit:        "C",
		Value:       nil,
	},
	"RFtempCR": {
		Rtype:       4,
		Offset:      788,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire right carcass temperature",
		Name:        "RFtempCR",
		Unit:        "C",
		Value:       nil,
	},
	"RFtempL": {
		Rtype:       4,
		Offset:      768,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire left surface temperature",
		Name:        "RFtempL",
		Unit:        "C",
		Value:       nil,
	},
	"RFtempM": {
		Rtype:       4,
		Offset:      772,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire middle surface temperature",
		Name:        "RFtempM",
		Unit:        "C",
		Value:       nil,
	},
	"RFtempR": {
		Rtype:       4,
		Offset:      776,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire right surface temperature",
		Name:        "RFtempR",
		Unit:        "C",
		Value:       nil,
	},
	"RFwearL": {
		Rtype:       4,
		Offset:      792,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire left percent tread remaining",
		Name:        "RFwearL",
		Unit:        "%",
		Value:       nil,
	},
	"RFwearM": {
		Rtype:       4,
		Offset:      796,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire middle percent tread remaining",
		Name:        "RFwearM",
		Unit:        "%",
		Value:       nil,
	},
	"RFwearR": {
		Rtype:       4,
		Offset:      800,
		Count:       1,
		CountAsTime: false,
		Description: "RF tire right percent tread remaining",
		Name:        "RFwearR",
		Unit:        "%",
		Value:       nil,
	},
	"ROLLFshockDefl": {
		Rtype:       4,
		Offset:      1028,
		Count:       1,
		CountAsTime: false,
		Description: "ROLLF shock deflection",
		Name:        "ROLLFshockDefl",
		Unit:        "m",
		Value:       nil,
	},
	"ROLLFshockVel": {
		Rtype:       4,
		Offset:      1032,
		Count:       1,
		CountAsTime: false,
		Description: "ROLLF shock velocity",
		Name:        "ROLLFshockVel",
		Unit:        "m/s",
		Value:       nil,
	},
	"ROLLRshockDefl": {
		Rtype:       4,
		Offset:      1044,
		Count:       1,
		CountAsTime: false,
		Description: "ROLLR shock deflection",
		Name:        "ROLLRshockDefl",
		Unit:        "m",
		Value:       nil,
	},
	"ROLLRshockVel": {
		Rtype:       4,
		Offset:      1048,
		Count:       1,
		CountAsTime: false,
		Description: "ROLLR shock velocity",
		Name:        "ROLLRshockVel",
		Unit:        "m/s",
		Value:       nil,
	},
	"RPM": {
		Rtype:       4,
		Offset:      205,
		Count:       1,
		CountAsTime: false,
		Description: "Engine rpm",
		Name:        "RPM",
		Unit:        "revs/min",
		Value:       nil,
	},
	"RRTiresAvailable": {
		Rtype:       2,
		Offset:      469,
		Count:       1,
		CountAsTime: false,
		Description: "How many right rear tires are remaining  255 is unlimited",
		Name:        "RRTiresAvailable",
		Unit:        "",
		Value:       nil,
	},
	"RRTiresUsed": {
		Rtype:       2,
		Offset:      433,
		Count:       1,
		CountAsTime: false,
		Description: "How many right rear tires used so far",
		Name:        "RRTiresUsed",
		Unit:        "",
		Value:       nil,
	},
	"RRcoldPressure": {
		Rtype:       4,
		Offset:      932,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire cold pressure  as set in the garage",
		Name:        "RRcoldPressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"RRpressure": {
		Rtype:       4,
		Offset:      928,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire pressure",
		Name:        "RRpressure",
		Unit:        "kPa",
		Value:       nil,
	},
	"RRrideHeight": {
		Rtype:       4,
		Offset:      1064,
		Count:       1,
		CountAsTime: false,
		Description: "RR ride height",
		Name:        "RRrideHeight",
		Unit:        "m",
		Value:       nil,
	},
	"RRspeed": {
		Rtype:       4,
		Offset:      924,
		Count:       1,
		CountAsTime: false,
		Description: "RR wheel speed",
		Name:        "RRspeed",
		Unit:        "m/s",
		Value:       nil,
	},
	"RRtempCL": {
		Rtype:       4,
		Offset:      948,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire left carcass temperature",
		Name:        "RRtempCL",
		Unit:        "C",
		Value:       nil,
	},
	"RRtempCM": {
		Rtype:       4,
		Offset:      952,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire middle carcass temperature",
		Name:        "RRtempCM",
		Unit:        "C",
		Value:       nil,
	},
	"RRtempCR": {
		Rtype:       4,
		Offset:      956,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire right carcass temperature",
		Name:        "RRtempCR",
		Unit:        "C",
		Value:       nil,
	},
	"RRtempL": {
		Rtype:       4,
		Offset:      936,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire left surface temperature",
		Name:        "RRtempL",
		Unit:        "C",
		Value:       nil,
	},
	"RRtempM": {
		Rtype:       4,
		Offset:      940,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire middle surface temperature",
		Name:        "RRtempM",
		Unit:        "C",
		Value:       nil,
	},
	"RRtempR": {
		Rtype:       4,
		Offset:      944,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire right surface temperature",
		Name:        "RRtempR",
		Unit:        "C",
		Value:       nil,
	},
	"RRwearL": {
		Rtype:       4,
		Offset:      960,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire left percent tread remaining",
		Name:        "RRwearL",
		Unit:        "%",
		Value:       nil,
	},
	"RRwearM": {
		Rtype:       4,
		Offset:      964,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire middle percent tread remaining",
		Name:        "RRwearM",
		Unit:        "%",
		Value:       nil,
	},
	"RRwearR": {
		Rtype:       4,
		Offset:      968,
		Count:       1,
		CountAsTime: false,
		Description: "RR tire right percent tread remaining",
		Name:        "RRwearR",
		Unit:        "%",
		Value:       nil,
	},
	"RearTireSetsAvailable": {
		Rtype:       2,
		Offset:      485,
		Count:       1,
		CountAsTime: false,
		Description: "How many rear tire sets are remaining  255 is unlimited",
		Name:        "RearTireSetsAvailable",
		Unit:        "",
		Value:       nil,
	},
	"RearTireSetsUsed": {
		Rtype:       2,
		Offset:      449,
		Count:       1,
		CountAsTime: false,
		Description: "How many rear tire sets used so far",
		Name:        "RearTireSetsUsed",
		Unit:        "",
		Value:       nil,
	},
	"RelativeHumidity": {
		Rtype:       4,
		Offset:      382,
		Count:       1,
		CountAsTime: false,
		Description: "Relative Humidity at start/finish line",
		Name:        "RelativeHumidity",
		Unit:        "%",
		Value:       nil,
	},
	"RightTireSetsAvailable": {
		Rtype:       2,
		Offset:      477,
		Count:       1,
		CountAsTime: false,
		Description: "How many right tire sets are remaining  255 is unlimited",
		Name:        "RightTireSetsAvailable",
		Unit:        "",
		Value:       nil,
	},
	"RightTireSetsUsed": {
		Rtype:       2,
		Offset:      441,
		Count:       1,
		CountAsTime: false,
		Description: "How many right tire sets used so far",
		Name:        "RightTireSetsUsed",
		Unit:        "",
		Value:       nil,
	},
	"Roll": {
		Rtype:       4,
		Offset:      318,
		Count:       1,
		CountAsTime: false,
		Description: "Roll orientation",
		Name:        "Roll",
		Unit:        "rad",
		Value:       nil,
	},
	"RollRate": {
		Rtype:       4,
		Offset:      664,
		Count:       1,
		CountAsTime: false,
		Description: "Roll rate",
		Name:        "RollRate",
		Unit:        "rad/s",
		Value:       nil,
	},
	"SessionFlags": {
		Rtype:       3,
		Offset:      24,
		Count:       1,
		CountAsTime: false,
		Description: "Session flags",
		Name:        "SessionFlags",
		Unit:        "irsdk_Flags",
		Value:       nil,
	},
	"SessionJokerLapsRemain": {
		Rtype:       2,
		Offset:      56,
		Count:       1,
		CountAsTime: false,
		Description: "Joker laps remaining to be taken",
		Name:        "SessionJokerLapsRemain",
		Unit:        "",
		Value:       nil,
	},
	"SessionLapsRemain": {
		Rtype:       2,
		Offset:      36,
		Count:       1,
		CountAsTime: false,
		Description: "Old laps left till session ends use SessionLapsRemainEx",
		Name:        "SessionLapsRemain",
		Unit:        "",
		Value:       nil,
	},
	"SessionLapsRemainEx": {
		Rtype:       2,
		Offset:      40,
		Count:       1,
		CountAsTime: false,
		Description: "New improved laps left till session ends",
		Name:        "SessionLapsRemainEx",
		Unit:        "",
		Value:       nil,
	},
	"SessionLapsTotal": {
		Rtype:       2,
		Offset:      52,
		Count:       1,
		CountAsTime: false,
		Description: "Total number of laps in session",
		Name:        "SessionLapsTotal",
		Unit:        "",
		Value:       nil,
	},
	"SessionNum": {
		Rtype:       2,
		Offset:      12,
		Count:       1,
		CountAsTime: false,
		Description: "Session number",
		Name:        "SessionNum",
		Unit:        "",
		Value:       nil,
	},
	"SessionOnJokerLap": {
		Rtype:       1,
		Offset:      60,
		Count:       1,
		CountAsTime: false,
		Description: "Player is currently completing a joker lap",
		Name:        "SessionOnJokerLap",
		Unit:        "",
		Value:       nil,
	},
	"SessionState": {
		Rtype:       2,
		Offset:      16,
		Count:       1,
		CountAsTime: false,
		Description: "Session state",
		Name:        "SessionState",
		Unit:        "irsdk_SessionState",
		Value:       nil,
	},
	"SessionTick": {
		Rtype:       2,
		Offset:      8,
		Count:       1,
		CountAsTime: false,
		Description: "Current update number",
		Name:        "SessionTick",
		Unit:        "",
		Value:       nil,
	},
	"SessionTime": {
		Rtype:       5,
		Offset:      0,
		Count:       1,
		CountAsTime: false,
		Description: "Seconds since session start",
		Name:        "SessionTime",
		Unit:        "s",
		Value:       nil,
	},
	"SessionTimeOfDay": {
		Rtype:       4,
		Offset:      61,
		Count:       1,
		CountAsTime: false,
		Description: "Time of day in seconds",
		Name:        "SessionTimeOfDay",
		Unit:        "s",
		Value:       nil,
	},
	"SessionTimeRemain": {
		Rtype:       5,
		Offset:      28,
		Count:       1,
		CountAsTime: false,
		Description: "Seconds left till session ends",
		Name:        "SessionTimeRemain",
		Unit:        "s",
		Value:       nil,
	},
	"SessionTimeTotal": {
		Rtype:       5,
		Offset:      44,
		Count:       1,
		CountAsTime: false,
		Description: "Total number of seconds in session",
		Name:        "SessionTimeTotal",
		Unit:        "s",
		Value:       nil,
	},
	"SessionUniqueID": {
		Rtype:       2,
		Offset:      20,
		Count:       1,
		CountAsTime: false,
		Description: "Session ID",
		Name:        "SessionUniqueID",
		Unit:        "",
		Value:       nil,
	},
	"ShiftGrindRPM": {
		Rtype:       4,
		Offset:      502,
		Count:       1,
		CountAsTime: false,
		Description: "RPM of shifter grinding noise",
		Name:        "ShiftGrindRPM",
		Unit:        "RPM",
		Value:       nil,
	},
	"ShiftIndicatorPct": {
		Rtype:       4,
		Offset:      596,
		Count:       1,
		CountAsTime: false,
		Description: "DEPRECATED use DriverCarSLBlinkRPM instead",
		Name:        "ShiftIndicatorPct",
		Unit:        "%",
		Value:       nil,
	},
	"ShiftPowerPct": {
		Rtype:       4,
		Offset:      498,
		Count:       1,
		CountAsTime: false,
		Description: "Friction torque applied to gears when shifting or grinding",
		Name:        "ShiftPowerPct",
		Unit:        "%",
		Value:       nil,
	},
	"Skies": {
		Rtype:       2,
		Offset:      362,
		Count:       1,
		CountAsTime: false,
		Description: "Skies (0=clear/1=p cloudy/2=m cloudy/3=overcast)",
		Name:        "Skies",
		Unit:        "",
		Value:       nil,
	},
	"SolarAltitude": {
		Rtype:       4,
		Offset:      394,
		Count:       1,
		CountAsTime: false,
		Description: "Sun angle above horizon in radians",
		Name:        "SolarAltitude",
		Unit:        "rad",
		Value:       nil,
	},
	"SolarAzimuth": {
		Rtype:       4,
		Offset:      398,
		Count:       1,
		CountAsTime: false,
		Description: "Sun angle clockwise from north in radians",
		Name:        "SolarAzimuth",
		Unit:        "rad",
		Value:       nil,
	},
	"Speed": {
		Rtype:       4,
		Offset:      302,
		Count:       1,
		CountAsTime: false,
		Description: "GPS vehicle speed",
		Name:        "Speed",
		Unit:        "m/s",
		Value:       nil,
	},
	"SteeringWheelAngle": {
		Rtype:       4,
		Offset:      185,
		Count:       1,
		CountAsTime: false,
		Description: "Steering wheel angle",
		Name:        "SteeringWheelAngle",
		Unit:        "rad",
		Value:       nil,
	},
	"SteeringWheelAngleMax": {
		Rtype:       4,
		Offset:      494,
		Count:       1,
		CountAsTime: false,
		Description: "Steering wheel max angle",
		Name:        "SteeringWheelAngleMax",
		Unit:        "rad",
		Value:       nil,
	},
	"SteeringWheelLimiter": {
		Rtype:       4,
		Offset:      587,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback limiter strength limits impacts and oscillation",
		Name:        "SteeringWheelLimiter",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelMaxForceNm": {
		Rtype:       4,
		Offset:      591,
		Count:       1,
		CountAsTime: false,
		Description: "Value of strength or max force slider in Nm for FFB",
		Name:        "SteeringWheelMaxForceNm",
		Unit:        "N*m",
		Value:       nil,
	},
	"SteeringWheelPctDamper": {
		Rtype:       4,
		Offset:      583,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max damping",
		Name:        "SteeringWheelPctDamper",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelPctIntensity": {
		Rtype:       4,
		Offset:      575,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max intensity",
		Name:        "SteeringWheelPctIntensity",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelPctSmoothing": {
		Rtype:       4,
		Offset:      579,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max smoothing",
		Name:        "SteeringWheelPctSmoothing",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelPctTorque": {
		Rtype:       4,
		Offset:      563,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max torque on steering shaft unsigned",
		Name:        "SteeringWheelPctTorque",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelPctTorqueSign": {
		Rtype:       4,
		Offset:      567,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max torque on steering shaft signed",
		Name:        "SteeringWheelPctTorqueSign",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelPctTorqueSignStops": {
		Rtype:       4,
		Offset:      571,
		Count:       1,
		CountAsTime: false,
		Description: "Force feedback % max torque on steering shaft signed stops",
		Name:        "SteeringWheelPctTorqueSignStops",
		Unit:        "%",
		Value:       nil,
	},
	"SteeringWheelTorque": {
		Rtype:       4,
		Offset:      640,
		Count:       1,
		CountAsTime: false,
		Description: "Output torque on steering shaft",
		Name:        "SteeringWheelTorque",
		Unit:        "N*m",
		Value:       nil,
	},
	"SteeringWheelTorque_ST": {
		Rtype:       4,
		Offset:      616,
		Count:       6,
		CountAsTime: true,
		Description: "Output torque on steering shaft at 360 Hz",
		Name:        "SteeringWheelTorque_ST",
		Unit:        "N*m",
		Value:       nil,
	},
	"SteeringWheelUseLinear": {
		Rtype:       1,
		Offset:      595,
		Count:       1,
		CountAsTime: false,
		Description: "True if steering wheel force is using linear mode",
		Name:        "SteeringWheelUseLinear",
		Unit:        "",
		Value:       nil,
	},
	"Throttle": {
		Rtype:       4,
		Offset:      189,
		Count:       1,
		CountAsTime: false,
		Description: "0=off throttle to 1=full throttle",
		Name:        "Throttle",
		Unit:        "%",
		Value:       nil,
	},
	"ThrottleRaw": {
		Rtype:       4,
		Offset:      506,
		Count:       1,
		CountAsTime: false,
		Description: "Raw throttle input 0=off throttle to 1=full throttle",
		Name:        "ThrottleRaw",
		Unit:        "%",
		Value:       nil,
	},
	"TireLF_RumblePitch": {
		Rtype:       4,
		Offset:      600,
		Count:       1,
		CountAsTime: false,
		Description: "Players LF Tire Sound rumblestrip pitch",
		Name:        "TireLF_RumblePitch",
		Unit:        "Hz",
		Value:       nil,
	},
	"TireLR_RumblePitch": {
		Rtype:       4,
		Offset:      608,
		Count:       1,
		CountAsTime: false,
		Description: "Players LR Tire Sound rumblestrip pitch",
		Name:        "TireLR_RumblePitch",
		Unit:        "Hz",
		Value:       nil,
	},
	"TireRF_RumblePitch": {
		Rtype:       4,
		Offset:      604,
		Count:       1,
		CountAsTime: false,
		Description: "Players RF Tire Sound rumblestrip pitch",
		Name:        "TireRF_RumblePitch",
		Unit:        "Hz",
		Value:       nil,
	},
	"TireRR_RumblePitch": {
		Rtype:       4,
		Offset:      612,
		Count:       1,
		CountAsTime: false,
		Description: "Players RR Tire Sound rumblestrip pitch",
		Name:        "TireRR_RumblePitch",
		Unit:        "Hz",
		Value:       nil,
	},
	"TireSetsAvailable": {
		Rtype:       2,
		Offset:      489,
		Count:       1,
		CountAsTime: false,
		Description: "How many tire sets are remaining  255 is unlimited",
		Name:        "TireSetsAvailable",
		Unit:        "",
		Value:       nil,
	},
	"TireSetsUsed": {
		Rtype:       2,
		Offset:      453,
		Count:       1,
		CountAsTime: false,
		Description: "How many tire sets used so far",
		Name:        "TireSetsUsed",
		Unit:        "",
		Value:       nil,
	},
	"TorqueMGU_K": {
		Rtype:       4,
		Offset:      892,
		Count:       1,
		CountAsTime: false,
		Description: "Engine MGU-K mechanical torque",
		Name:        "TorqueMGU_K",
		Unit:        "Nm",
		Value:       nil,
	},
	"TrackTemp": {
		Rtype:       4,
		Offset:      346,
		Count:       1,
		CountAsTime: false,
		Description: "Deprecated  set to TrackTempCrew",
		Name:        "TrackTemp",
		Unit:        "C",
		Value:       nil,
	},
	"TrackTempCrew": {
		Rtype:       4,
		Offset:      350,
		Count:       1,
		CountAsTime: false,
		Description: "Temperature of track measured by crew around track",
		Name:        "TrackTempCrew",
		Unit:        "C",
		Value:       nil,
	},
	"TrackWetness": {
		Rtype:       2,
		Offset:      358,
		Count:       1,
		CountAsTime: false,
		Description: "How wet is the average track surface",
		Name:        "TrackWetness",
		Unit:        "irsdk_TrackWetness",
		Value:       nil,
	},
	"VelocityX": {
		Rtype:       4,
		Offset:      652,
		Count:       1,
		CountAsTime: false,
		Description: "X velocity",
		Name:        "VelocityX",
		Unit:        "m/s",
		Value:       nil,
	},
	"VelocityY": {
		Rtype:       4,
		Offset:      648,
		Count:       1,
		CountAsTime: false,
		Description: "Y velocity",
		Name:        "VelocityY",
		Unit:        "m/s",
		Value:       nil,
	},
	"VelocityZ": {
		Rtype:       4,
		Offset:      644,
		Count:       1,
		CountAsTime: false,
		Description: "Z velocity",
		Name:        "VelocityZ",
		Unit:        "m/s",
		Value:       nil,
	},
	"VertAccel": {
		Rtype:       4,
		Offset:      668,
		Count:       1,
		CountAsTime: false,
		Description: "Vertical acceleration (including gravity)",
		Name:        "VertAccel",
		Unit:        "m/s^2",
		Value:       nil,
	},
	"Voltage": {
		Rtype:       4,
		Offset:      856,
		Count:       1,
		CountAsTime: false,
		Description: "Engine voltage",
		Name:        "Voltage",
		Unit:        "V",
		Value:       nil,
	},
	"WaterLevel": {
		Rtype:       4,
		Offset:      864,
		Count:       1,
		CountAsTime: false,
		Description: "Engine coolant level",
		Name:        "WaterLevel",
		Unit:        "l",
		Value:       nil,
	},
	"WaterTemp": {
		Rtype:       4,
		Offset:      860,
		Count:       1,
		CountAsTime: false,
		Description: "Engine coolant temp",
		Name:        "WaterTemp",
		Unit:        "C",
		Value:       nil,
	},
	"WeatherDeclaredWet": {
		Rtype:       1,
		Offset:      402,
		Count:       1,
		CountAsTime: false,
		Description: "The steward says rain tires can be used",
		Name:        "WeatherDeclaredWet",
		Unit:        "",
		Value:       nil,
	},
	"WindDir": {
		Rtype:       4,
		Offset:      378,
		Count:       1,
		CountAsTime: false,
		Description: "Wind direction at start/finish line",
		Name:        "WindDir",
		Unit:        "rad",
		Value:       nil,
	},
	"WindVel": {
		Rtype:       4,
		Offset:      374,
		Count:       1,
		CountAsTime: false,
		Description: "Wind velocity at start/finish line",
		Name:        "WindVel",
		Unit:        "m/s",
		Value:       nil,
	},
	"Yaw": {
		Rtype:       4,
		Offset:      306,
		Count:       1,
		CountAsTime: false,
		Description: "Yaw orientation",
		Name:        "Yaw",
		Unit:        "rad",
		Value:       nil,
	},
	"YawNorth": {
		Rtype:       4,
		Offset:      310,
		Count:       1,
		CountAsTime: false,
		Description: "Yaw orientation relative to north",
		Name:        "YawNorth",
		Unit:        "rad",
		Value:       nil,
	},
	"YawRate": {
		Rtype:       4,
		Offset:      656,
		Count:       1,
		CountAsTime: false,
		Description: "Yaw rate",
		Name:        "YawRate",
		Unit:        "rad/s",
		Value:       nil,
	},
	"dcBrakeBias": {
		Rtype:       4,
		Offset:      696,
		Count:       1,
		CountAsTime: false,
		Description: "In car brake bias adjustment",
		Name:        "dcBrakeBias",
		Unit:        "",
		Value:       nil,
	},
	"dcBrakeBiasFine": {
		Rtype:       4,
		Offset:      700,
		Count:       1,
		CountAsTime: false,
		Description: "In car brake bias fine adjustment",
		Name:        "dcBrakeBiasFine",
		Unit:        "",
		Value:       nil,
	},
	"dcBrakeMisc": {
		Rtype:       4,
		Offset:      708,
		Count:       1,
		CountAsTime: false,
		Description: "In car brake misc adjustment",
		Name:        "dcBrakeMisc",
		Unit:        "",
		Value:       nil,
	},
	"dcDRSToggle": {
		Rtype:       1,
		Offset:      682,
		Count:       1,
		CountAsTime: false,
		Description: "In car toggle DRS",
		Name:        "dcDRSToggle",
		Unit:        "",
		Value:       nil,
	},
	"dcDashPage": {
		Rtype:       4,
		Offset:      736,
		Count:       1,
		CountAsTime: false,
		Description: "In car dash display page adjustment",
		Name:        "dcDashPage",
		Unit:        "",
		Value:       nil,
	},
	"dcDiffEntry": {
		Rtype:       4,
		Offset:      740,
		Count:       1,
		CountAsTime: false,
		Description: "In car diff entry adjustment",
		Name:        "dcDiffEntry",
		Unit:        "",
		Value:       nil,
	},
	"dcDiffExit": {
		Rtype:       4,
		Offset:      748,
		Count:       1,
		CountAsTime: false,
		Description: "In car diff exit adjustment",
		Name:        "dcDiffExit",
		Unit:        "",
		Value:       nil,
	},
	"dcDiffMiddle": {
		Rtype:       4,
		Offset:      744,
		Count:       1,
		CountAsTime: false,
		Description: "In car diff middle adjustment",
		Name:        "dcDiffMiddle",
		Unit:        "",
		Value:       nil,
	},
	"dcEngineBraking": {
		Rtype:       4,
		Offset:      712,
		Count:       1,
		CountAsTime: false,
		Description: "In car engine braking adjustment",
		Name:        "dcEngineBraking",
		Unit:        "",
		Value:       nil,
	},
	"dcMGUKDeployMode": {
		Rtype:       4,
		Offset:      732,
		Count:       1,
		CountAsTime: false,
		Description: "In car MGU-K deployment mode level adjustment",
		Name:        "dcMGUKDeployMode",
		Unit:        "",
		Value:       nil,
	},
	"dcPeakBrakeBias": {
		Rtype:       4,
		Offset:      704,
		Count:       1,
		CountAsTime: false,
		Description: "In car peak brake bias adjustment",
		Name:        "dcPeakBrakeBias",
		Unit:        "",
		Value:       nil,
	},
	"dcPitSpeedLimiterToggle": {
		Rtype:       1,
		Offset:      681,
		Count:       1,
		CountAsTime: false,
		Description: "In car traction control active",
		Name:        "dcPitSpeedLimiterToggle",
		Unit:        "",
		Value:       nil,
	},
	"dcStarter": {
		Rtype:       1,
		Offset:      680,
		Count:       1,
		CountAsTime: false,
		Description: "In car trigger car starter",
		Name:        "dcStarter",
		Unit:        "",
		Value:       nil,
	},
	"dcTearOffVisor": {
		Rtype:       1,
		Offset:      683,
		Count:       1,
		CountAsTime: false,
		Description: "In car tear off visor film",
		Name:        "dcTearOffVisor",
		Unit:        "",
		Value:       nil,
	},
	"dpFastRepair": {
		Rtype:       4,
		Offset:      688,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop fast repair set",
		Name:        "dpFastRepair",
		Unit:        "",
		Value:       nil,
	},
	"dpLFTireColdPress": {
		Rtype:       4,
		Offset:      716,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop lf tire cold pressure adjustment",
		Name:        "dpLFTireColdPress",
		Unit:        "Pa",
		Value:       nil,
	},
	"dpLRTireColdPress": {
		Rtype:       4,
		Offset:      724,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop lr tire cold pressure adjustment",
		Name:        "dpLRTireColdPress",
		Unit:        "Pa",
		Value:       nil,
	},
	"dpRFTireColdPress": {
		Rtype:       4,
		Offset:      720,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop rf cold tire pressure adjustment",
		Name:        "dpRFTireColdPress",
		Unit:        "Pa",
		Value:       nil,
	},
	"dpRRTireColdPress": {
		Rtype:       4,
		Offset:      728,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop rr cold tire pressure adjustment",
		Name:        "dpRRTireColdPress",
		Unit:        "Pa",
		Value:       nil,
	},
	"dpTireChange": {
		Rtype:       4,
		Offset:      684,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop all tire change request",
		Name:        "dpTireChange",
		Unit:        "",
		Value:       nil,
	},
	"dpWingFront": {
		Rtype:       4,
		Offset:      692,
		Count:       1,
		CountAsTime: false,
		Description: "Pitstop front wing adjustment",
		Name:        "dpWingFront",
		Unit:        "",
		Value:       nil,
	},
}

func TestAvailableVars(t *testing.T) {
	t.Run("test valid vars", func(t *testing.T) {
		tVar := map[string]VarHeader{"A": {}, "B": {}}

		availableVars := AvailableVars(tVar)

		if availableVars[0] != "A" && availableVars[1] != "B" {
			t.Errorf("expected return values to be [A, B], received %v", availableVars)
		}
	})

	t.Run("test empty vars map", func(t *testing.T) {
		tVar := make(map[string]VarHeader)

		availableVars := AvailableVars(tVar)

		if len(availableVars) > 0 {
			t.Errorf("expected available vars to be empty. received %v", availableVars)
		}
	})

	t.Run("test nil vars map", func(t *testing.T) {
		var tVar map[string]VarHeader = nil

		availableVars := AvailableVars(tVar)

		if len(availableVars) > 0 {
			t.Errorf("expected available vars to be empty. received %v", availableVars)
		}
	})

}
